{"type": "indicator", "spec_version": "2.1", "id": "indicator--251d09da-4cfe-4e29-8402-e08c0009c2c0", "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81", "created": "2022-10-16T06:15:00.000Z", "modified": "2022-11-24T16:15:00.000Z", "name": "CVE-2022-41323", "description": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression.", "indicator_types": ["compromised"], "pattern": "[(software:cpe='cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*' OR software:cpe='cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*' OR software:cpe='cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*')]", "pattern_type": "stix", "pattern_version": "2.1", "valid_from": "2022-10-16T06:15:00Z", "external_references": [{"source_name": "cve2stix", "description": "This object was created using cve2stix from the Signals Corps.", "url": "https://github.com/signalscorps/cve2stix"}], "object_marking_refs": ["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"], "extensions": {"extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {"extension_type": "property-extension", "all_cpe23uris": ["cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"], "vulnerable_cpeid": ["cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"]}}}