{
    "type": "bundle",
    "id": "bundle--1da6014e-e52d-4359-aa3a-9273263ae70a",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--2d3c54af-bcc6-4be4-8f33-12c912595d5f",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-18T22:15:00.000Z",
            "modified": "2022-11-20T02:44:00.000Z",
            "name": "CVE-2022-41884",
            "description": "TensorFlow is an open source platform for machine learning. If a numpy array is created with a shape such that one element is zero and the others sum to a large number, an error will be raised. We have patched the issue in GitHub commit 2b56169c16e375c521a3bc8ea658811cc0793784. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-41884"
                },
                {
                    "source_name": "cwe",
                    "external_id": "CWE-670"
                },
                {
                    "source_name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-jq6x-99hj-q636",
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-jq6x-99hj-q636"
                },
                {
                    "source_name": "https://github.com/tensorflow/tensorflow/commit/2b56169c16e375c521a3bc8ea658811cc0793784",
                    "url": "https://github.com/tensorflow/tensorflow/commit/2b56169c16e375c521a3bc8ea658811cc0793784"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2022-41884",
                            "ASSIGNER": "security-advisories@github.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "CWE-670"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-jq6x-99hj-q636",
                                    "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-jq6x-99hj-q636",
                                    "refsource": "CONFIRM",
                                    "tags": []
                                },
                                {
                                    "url": "https://github.com/tensorflow/tensorflow/commit/2b56169c16e375c521a3bc8ea658811cc0793784",
                                    "name": "https://github.com/tensorflow/tensorflow/commit/2b56169c16e375c521a3bc8ea658811cc0793784",
                                    "refsource": "MISC",
                                    "tags": []
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "TensorFlow is an open source platform for machine learning. If a numpy array is created with a shape such that one element is zero and the others sum to a large number, an error will be raised. We have patched the issue in GitHub commit 2b56169c16e375c521a3bc8ea658811cc0793784. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range."
                                }
                            ]
                        }
                    },
                    "configurations": {
                        "CVE_data_version": "4.0",
                        "nodes": []
                    },
                    "impact": {},
                    "publishedDate": "2022-11-18T22:15Z",
                    "lastModifiedDate": "2022-11-20T02:44Z"
                }
            }
        }
    ]
}