{
    "type": "bundle",
    "id": "bundle--c80d6972-c772-47de-932c-f0464bd7c12f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0adfe752-63d0-41b4-9b0b-3deaa20cc92f",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-09-09T21:15:00.000Z",
            "modified": "2022-11-10T03:55:00.000Z",
            "name": "CVE-2022-36087",
            "description": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-36087"
                },
                {
                    "source_name": "cwe",
                    "external_id": "CWE-20"
                },
                {
                    "source_name": "https://github.com/oauthlib/oauthlib/blob/2b8a44855a51ad5a5b0c348a08c2564a2e197ea2/oauthlib/uri_validate.py",
                    "url": "https://github.com/oauthlib/oauthlib/blob/2b8a44855a51ad5a5b0c348a08c2564a2e197ea2/oauthlib/uri_validate.py"
                },
                {
                    "source_name": "https://github.com/oauthlib/oauthlib/releases/tag/v3.2.1",
                    "url": "https://github.com/oauthlib/oauthlib/releases/tag/v3.2.1"
                },
                {
                    "source_name": "https://github.com/oauthlib/oauthlib/blob/d4bafd9f1d0eba3766e933b1ac598cbbf37b8914/oauthlib/oauth2/rfc6749/grant_types/base.py#L232",
                    "url": "https://github.com/oauthlib/oauthlib/blob/d4bafd9f1d0eba3766e933b1ac598cbbf37b8914/oauthlib/oauth2/rfc6749/grant_types/base.py#L232"
                },
                {
                    "source_name": "https://github.com/oauthlib/oauthlib/security/advisories/GHSA-3pgj-pg6c-r5p7",
                    "url": "https://github.com/oauthlib/oauthlib/security/advisories/GHSA-3pgj-pg6c-r5p7"
                },
                {
                    "source_name": "https://github.com/oauthlib/oauthlib/commit/2e40b412c844ecc4673c3fa3f72181f228bdbacd",
                    "url": "https://github.com/oauthlib/oauthlib/commit/2e40b412c844ecc4673c3fa3f72181f228bdbacd"
                },
                {
                    "source_name": "FEDORA-2022-5a74a5eea7",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRYLYHE5HWF6R2CRLJFUK4PILR47WXOE/"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2022-36087",
                            "ASSIGNER": "security-advisories@github.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "CWE-20"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://github.com/oauthlib/oauthlib/blob/2b8a44855a51ad5a5b0c348a08c2564a2e197ea2/oauthlib/uri_validate.py",
                                    "name": "https://github.com/oauthlib/oauthlib/blob/2b8a44855a51ad5a5b0c348a08c2564a2e197ea2/oauthlib/uri_validate.py",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Exploit",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://github.com/oauthlib/oauthlib/releases/tag/v3.2.1",
                                    "name": "https://github.com/oauthlib/oauthlib/releases/tag/v3.2.1",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://github.com/oauthlib/oauthlib/blob/d4bafd9f1d0eba3766e933b1ac598cbbf37b8914/oauthlib/oauth2/rfc6749/grant_types/base.py#L232",
                                    "name": "https://github.com/oauthlib/oauthlib/blob/d4bafd9f1d0eba3766e933b1ac598cbbf37b8914/oauthlib/oauth2/rfc6749/grant_types/base.py#L232",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Exploit",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://github.com/oauthlib/oauthlib/security/advisories/GHSA-3pgj-pg6c-r5p7",
                                    "name": "https://github.com/oauthlib/oauthlib/security/advisories/GHSA-3pgj-pg6c-r5p7",
                                    "refsource": "CONFIRM",
                                    "tags": [
                                        "Exploit",
                                        "Mitigation",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://github.com/oauthlib/oauthlib/commit/2e40b412c844ecc4673c3fa3f72181f228bdbacd",
                                    "name": "https://github.com/oauthlib/oauthlib/commit/2e40b412c844ecc4673c3fa3f72181f228bdbacd",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Patch",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRYLYHE5HWF6R2CRLJFUK4PILR47WXOE/",
                                    "name": "FEDORA-2022-5a74a5eea7",
                                    "refsource": "FEDORA",
                                    "tags": [
                                        "Mailing List",
                                        "Third Party Advisory"
                                    ]
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds."
                                }
                            ]
                        }
                    },
                    "impact": {
                        "baseMetricV3": {
                            "cvssV3": {
                                "version": "3.1",
                                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                                "attackVector": "NETWORK",
                                "attackComplexity": "LOW",
                                "privilegesRequired": "NONE",
                                "userInteraction": "REQUIRED",
                                "scope": "UNCHANGED",
                                "confidentialityImpact": "NONE",
                                "integrityImpact": "NONE",
                                "availabilityImpact": "HIGH",
                                "baseScore": 6.5,
                                "baseSeverity": "MEDIUM"
                            },
                            "exploitabilityScore": 2.8,
                            "impactScore": 3.6
                        }
                    },
                    "publishedDate": "2022-09-09T21:15Z",
                    "lastModifiedDate": "2022-11-10T03:55Z"
                }
            }
        },
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--21116862-2417-46a1-95f4-95573ca566dc",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-09-09T21:15:00.000Z",
            "modified": "2022-11-10T03:55:00.000Z",
            "name": "CVE-2022-36087",
            "description": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.",
            "indicator_types": [
                "compromised"
            ],
            "pattern": "[(software:cpe='cpe:2.3:a:oauthlib_project:oauthlib:*:*:*:*:*:*:*:*') OR (software:cpe='cpe:2.3:o:fedoraproject:fedora:37:*:*:*:*:*:*:*')]",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2022-09-09T21:15:00Z",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
                    "extension_type": "property-extension",
                    "all_cpe23uris": [
                        "cpe:2.3:a:oauthlib_project:oauthlib:*:*:*:*:*:*:*:*",
                        "cpe:2.3:o:fedoraproject:fedora:37:*:*:*:*:*:*:*"
                    ],
                    "vulnerable_cpeid": [
                        "cpe:2.3:a:oauthlib_project:oauthlib:*:*:*:*:*:*:*:*",
                        "cpe:2.3:o:fedoraproject:fedora:37:*:*:*:*:*:*:*"
                    ]
                }
            }
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--ed80d286-56ce-4099-aa0d-875763f475a2",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-09-09T21:15:00.000Z",
            "modified": "2022-11-10T03:55:00.000Z",
            "relationship_type": "identifies",
            "source_ref": "indicator--21116862-2417-46a1-95f4-95573ca566dc",
            "target_ref": "vulnerability--0adfe752-63d0-41b4-9b0b-3deaa20cc92f",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ]
        }
    ]
}