{"type": "vulnerability", "spec_version": "2.1", "id": "vulnerability--e280774b-3875-4cb1-a2d0-657d62baa6f4", "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81", "created": "2022-11-18T22:15:00.000Z", "modified": "2022-11-20T02:44:00.000Z", "name": "CVE-2022-41893", "description": "TensorFlow is an open source platform for machine learning. If `tf.raw_ops.TensorListResize` is given a nonscalar value for input `size`, it results `CHECK` fail which can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 888e34b49009a4e734c27ab0c43b0b5102682c56. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range.", "external_references": [{"source_name": "cve", "external_id": "CVE-2022-41893"}, {"source_name": "cwe", "external_id": "CWE-617"}, {"source_name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-67pf-62xr-q35m", "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-67pf-62xr-q35m"}, {"source_name": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/list_kernels.cc", "url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/list_kernels.cc"}, {"source_name": "https://github.com/tensorflow/tensorflow/commit/888e34b49009a4e734c27ab0c43b0b5102682c56", "url": "https://github.com/tensorflow/tensorflow/commit/888e34b49009a4e734c27ab0c43b0b5102682c56"}, {"source_name": "cve2stix", "description": "This object was created using cve2stix from the Signals Corps.", "url": "https://github.com/signalscorps/cve2stix"}], "object_marking_refs": ["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"], "extensions": {"extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {"extension_type": "property-extension", "nvd_cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2022-41893", "ASSIGNER": "security-advisories@github.com"}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-617"}]}]}, "references": {"reference_data": [{"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-67pf-62xr-q35m", "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-67pf-62xr-q35m", "refsource": "CONFIRM", "tags": []}, {"url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/list_kernels.cc", "name": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/list_kernels.cc", "refsource": "MISC", "tags": []}, {"url": "https://github.com/tensorflow/tensorflow/commit/888e34b49009a4e734c27ab0c43b0b5102682c56", "name": "https://github.com/tensorflow/tensorflow/commit/888e34b49009a4e734c27ab0c43b0b5102682c56", "refsource": "MISC", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "TensorFlow is an open source platform for machine learning. If `tf.raw_ops.TensorListResize` is given a nonscalar value for input `size`, it results `CHECK` fail which can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 888e34b49009a4e734c27ab0c43b0b5102682c56. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2022-11-18T22:15Z", "lastModifiedDate": "2022-11-20T02:44Z"}}}