{
    "type": "bundle",
    "id": "bundle--6811d54c-7901-450d-9f53-d628c529159a",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--14a23158-b18f-4d6f-b681-2b7b397eccb6",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-08-29T15:15:00.000Z",
            "modified": "2022-10-01T02:31:00.000Z",
            "name": "CVE-2022-0718",
            "description": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-0718"
                },
                {
                    "source_name": "cwe",
                    "external_id": "CWE-522"
                },
                {
                    "source_name": "https://security-tracker.debian.org/tracker/CVE-2022-0718",
                    "url": "https://security-tracker.debian.org/tracker/CVE-2022-0718"
                },
                {
                    "source_name": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850"
                },
                {
                    "source_name": "https://access.redhat.com/security/cve/CVE-2022-0718",
                    "url": "https://access.redhat.com/security/cve/CVE-2022-0718"
                },
                {
                    "source_name": "https://bugs.launchpad.net/oslo.utils/+bug/1949623",
                    "url": "https://bugs.launchpad.net/oslo.utils/+bug/1949623"
                },
                {
                    "source_name": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa",
                    "url": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
                },
                {
                    "source_name": "[debian-lts-announce] 20220913 [SECURITY] [DLA 3106-1] python-oslo.utils security update",
                    "url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2022-0718",
                            "ASSIGNER": "secalert@redhat.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "CWE-522"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://security-tracker.debian.org/tracker/CVE-2022-0718",
                                    "name": "https://security-tracker.debian.org/tracker/CVE-2022-0718",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Patch",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850",
                                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Issue Tracking",
                                        "Patch",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://access.redhat.com/security/cve/CVE-2022-0718",
                                    "name": "https://access.redhat.com/security/cve/CVE-2022-0718",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://bugs.launchpad.net/oslo.utils/+bug/1949623",
                                    "name": "https://bugs.launchpad.net/oslo.utils/+bug/1949623",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Exploit",
                                        "Issue Tracking",
                                        "Patch",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa",
                                    "name": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Patch",
                                        "Vendor Advisory"
                                    ]
                                },
                                {
                                    "url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html",
                                    "name": "[debian-lts-announce] 20220913 [SECURITY] [DLA 3106-1] python-oslo.utils security update",
                                    "refsource": "MLIST",
                                    "tags": [
                                        "Mailing List",
                                        "Third Party Advisory"
                                    ]
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext."
                                }
                            ]
                        }
                    },
                    "impact": {
                        "baseMetricV3": {
                            "cvssV3": {
                                "version": "3.1",
                                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
                                "attackVector": "NETWORK",
                                "attackComplexity": "LOW",
                                "privilegesRequired": "HIGH",
                                "userInteraction": "NONE",
                                "scope": "UNCHANGED",
                                "confidentialityImpact": "HIGH",
                                "integrityImpact": "NONE",
                                "availabilityImpact": "NONE",
                                "baseScore": 4.9,
                                "baseSeverity": "MEDIUM"
                            },
                            "exploitabilityScore": 1.2,
                            "impactScore": 3.6
                        }
                    },
                    "publishedDate": "2022-08-29T15:15Z",
                    "lastModifiedDate": "2022-10-01T02:31Z"
                }
            }
        },
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--158e0261-5401-4c2d-a8f4-0b72dd513d99",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-08-29T15:15:00.000Z",
            "modified": "2022-10-01T02:31:00.000Z",
            "name": "CVE-2022-0718",
            "description": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext.",
            "indicator_types": [
                "compromised"
            ],
            "pattern": "[(software:cpe='cpe:2.3:a:openstack:oslo.utils:*:*:*:*:*:*:*:*' OR software:cpe='cpe:2.3:a:openstack:oslo.utils:4.12.0:*:*:*:*:*:*:*') OR (software:cpe='cpe:2.3:a:redhat:openshift_container_platform:4.0:*:*:*:*:*:*:*' OR software:cpe='cpe:2.3:a:redhat:openstack_platform:16.1:*:*:*:*:*:*:*') OR (software:cpe='cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*' OR software:cpe='cpe:2.3:o:debian:debian_linux:11.0:*:*:*:*:*:*:*')]",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2022-08-29T15:15:00Z",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
                    "extension_type": "property-extension",
                    "all_cpe23uris": [
                        "cpe:2.3:o:debian:debian_linux:11.0:*:*:*:*:*:*:*",
                        "cpe:2.3:a:openstack:oslo.utils:4.12.0:*:*:*:*:*:*:*",
                        "cpe:2.3:a:redhat:openshift_container_platform:4.0:*:*:*:*:*:*:*",
                        "cpe:2.3:a:openstack:oslo.utils:*:*:*:*:*:*:*:*",
                        "cpe:2.3:a:redhat:openstack_platform:16.1:*:*:*:*:*:*:*",
                        "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*"
                    ],
                    "vulnerable_cpeid": [
                        "cpe:2.3:o:debian:debian_linux:11.0:*:*:*:*:*:*:*",
                        "cpe:2.3:a:openstack:oslo.utils:4.12.0:*:*:*:*:*:*:*",
                        "cpe:2.3:a:redhat:openshift_container_platform:4.0:*:*:*:*:*:*:*",
                        "cpe:2.3:a:openstack:oslo.utils:*:*:*:*:*:*:*:*",
                        "cpe:2.3:a:redhat:openstack_platform:16.1:*:*:*:*:*:*:*",
                        "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*"
                    ]
                }
            }
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--e624ab02-143e-4867-86d8-42697c48a759",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-08-29T15:15:00.000Z",
            "modified": "2022-10-01T02:31:00.000Z",
            "relationship_type": "identifies",
            "source_ref": "indicator--158e0261-5401-4c2d-a8f4-0b72dd513d99",
            "target_ref": "vulnerability--14a23158-b18f-4d6f-b681-2b7b397eccb6",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ]
        }
    ]
}