{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--29b90cfb-783b-40d0-9bf3-0168c1502d89",
    "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
    "created": "2021-03-30T02:15:00.000Z",
    "modified": "2021-04-02T12:50:00.000Z",
    "name": "CVE-2018-1110",
    "description": "A flaw was found in knot-resolver before version 2.3.0. Malformed DNS messages may cause denial of service.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2018-1110"
        },
        {
            "source_name": "cwe",
            "external_id": "CWE-20"
        },
        {
            "source_name": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328",
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328"
        },
        {
            "source_name": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html",
            "url": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html"
        },
        {
            "source_name": "cve2stix",
            "description": "This object was created using cve2stix from the Signals Corps.",
            "url": "https://github.com/signalscorps/cve2stix"
        }
    ],
    "object_marking_refs": [
        "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
    ],
    "extensions": {
        "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
            "extension_type": "property-extension",
            "impact": {
                "baseMetricV2": {
                    "acInsufInfo": false,
                    "cvssV2": {
                        "accessComplexity": "LOW",
                        "accessVector": "NETWORK",
                        "authentication": "NONE",
                        "availabilityImpact": "PARTIAL",
                        "baseScore": 5.0,
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
                        "version": "2.0"
                    },
                    "exploitabilityScore": 10.0,
                    "impactScore": 2.9,
                    "obtainAllPrivilege": false,
                    "obtainOtherPrivilege": false,
                    "obtainUserPrivilege": false,
                    "severity": "MEDIUM",
                    "userInteractionRequired": false
                },
                "baseMetricV3": {
                    "cvssV3": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.5,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    },
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                }
            },
            "lastModifiedDate": "2021-04-02T12:50Z",
            "nvd_cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2018-1110"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "A flaw was found in knot-resolver before version 2.3.0. Malformed DNS messages may cause denial of service."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "en",
                                    "value": "CWE-20"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328",
                            "refsource": "MISC",
                            "tags": [
                                "Issue Tracking",
                                "Third Party Advisory"
                            ]
                        },
                        {
                            "name": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html",
                            "url": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html",
                            "refsource": "MISC",
                            "tags": [
                                "Release Notes",
                                "Vendor Advisory"
                            ]
                        }
                    ]
                }
            },
            "publishedDate": "2021-03-30T02:15Z"
        }
    }
}