{
    "type": "indicator",
    "spec_version": "2.1",
    "id": "indicator--21116862-2417-46a1-95f4-95573ca566dc",
    "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
    "created": "2022-09-09T21:15:00.000Z",
    "modified": "2022-11-10T03:55:00.000Z",
    "name": "CVE-2022-36087",
    "description": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.",
    "indicator_types": [
        "compromised"
    ],
    "pattern": "[(software:cpe='cpe:2.3:a:oauthlib_project:oauthlib:*:*:*:*:*:*:*:*') OR (software:cpe='cpe:2.3:o:fedoraproject:fedora:37:*:*:*:*:*:*:*')]",
    "pattern_type": "stix",
    "pattern_version": "2.1",
    "valid_from": "2022-09-09T21:15:00Z",
    "external_references": [
        {
            "source_name": "cve2stix",
            "description": "This object was created using cve2stix from the Signals Corps.",
            "url": "https://github.com/signalscorps/cve2stix"
        }
    ],
    "object_marking_refs": [
        "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
    ],
    "extensions": {
        "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
            "all_cpe23uris": [
                "cpe:2.3:a:oauthlib_project:oauthlib:*:*:*:*:*:*:*:*",
                "cpe:2.3:o:fedoraproject:fedora:37:*:*:*:*:*:*:*"
            ],
            "extension_type": "property-extension",
            "vulnerable_cpeid": [
                "cpe:2.3:a:oauthlib_project:oauthlib:*:*:*:*:*:*:*:*",
                "cpe:2.3:o:fedoraproject:fedora:37:*:*:*:*:*:*:*"
            ]
        }
    }
}